routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', function () {
    if (auth()->check()) {
        return redirect()->route('admin.dashboard');
    }

    return redirect()->route('auth.index');
});

Route::name('auth.')->group(function () {
    Route::get('login', [\App\Http\Controllers\Admin\AuthController::class, 'index'])->name('index');
    Route::post('login', [\App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login');
    Route::post('logout', function () {
        auth()->logout();
        return response(['status' => true, 'redirect' => route('auth.index')]);
    })->name('logout')->middleware('auth');
});

Route::middleware('auth')->group(function () {
    Route::prefix('admin/')->name('admin.')->group(function () {
        Route::get('dashboard', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');

        Route::prefix('user/')->name('user.')->group(function () {
            Route::get('', [\App\Http\Controllers\Admin\UserController::class, 'index'])->name('index');
            Route::post('', [\App\Http\Controllers\Admin\UserController::class, 'create'])->name('create');
            Route::get('datatable', [\App\Http\Controllers\Admin\UserController::class, 'datatable'])->name('datatable');
            Route::get('{user_id}', [\App\Http\Controllers\Admin\UserController::class, 'get'])->name('get');
            Route::put('{user_id}', [\App\Http\Controllers\Admin\UserController::class, 'update'])->name('update');
            Route::delete('{user_id}', [\App\Http\Controllers\Admin\UserController::class, 'delete'])->name('delete');
            Route::get('{user_id}/group', [\App\Http\Controllers\Admin\UserController::class, 'getUserGroup'])->name('get-user-group');
            Route::put('{user_id}/group', [\App\Http\Controllers\Admin\UserController::class, 'updateUserGroup'])->name('update-user-group');
        });
    });
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
    ];
}

app/Models/GroupUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GroupUser extends Model
{
    use HasFactory;

    protected $table = 'roles';

    /**
     * The attributes thata are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'group_id',
        'user_id',
    ];

    /**
     * Connection GroupUser Model with User Model
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Connection GroupUser Model wuth Group Model
     */
    public function groups()
    {
        return $this->hasMany(Group::class);
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected static function booted()
    {
        static::deleting(function (User $user) {
            if ($user->id == 1) return false;
        });
    }

    public function getGroupIdsAttribute()
    {
        return $this->groups->pluck('id');
    }

    public function groups()
    {
        return $this->belongsToMany(Group::class, 'roles')->withTimestamps();
    }

    public function group_user()
    {
        return $this->hasOne(GroupUser::class);
    }
}

app/Http/Controllers/Admin/AuthController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Auth\LoginPostRequest;
use App\Models\User;
use Illuminate\Http\Response;

class AuthController extends Controller
{
    public function index()
    {
        if (auth()->check()) {
            return redirect()->route('admin.dashboard');
        }

        return view('login');
    }

    public function login(LoginPostRequest $request)
    {
        $user = User::where('username', $request->username)->first();

        if ($user) {
            if (auth()->attempt($request->only(['username', 'password']), $request->remember_me)) {
                $request->session()->regenerate();

                return response(
                    ['status' => true, 'redirect' => redirect()->intended(route('admin.dashboard'))->getTargetUrl()]
                );
            }

            return response(
                ['message' => 'Invalid username or password', 'redirect' => ''],
                Response::HTTP_BAD_REQUEST
            );
        }

        return response(['message' => 'Unauthorized user', 'redirect' => ''], Response::HTTP_BAD_REQUEST);
    }
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

class DashboardController
{
    public function index()
    {

        return view('admin.dashboard.index');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Repository\UserRepository;
use App\Http\Requests\Admin\User\UserCreateRequest;
use App\Http\Requests\Admin\User\UserUpdateGroupRequest;
use App\Http\Requests\Admin\User\UserUpdateRequest;
use App\Models\Group;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class UserController
{
    /**
     * @var UserRepository
     */
    private $repository;

    public function __construct(UserRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $groups = Group::all();
        return view('admin.user.index', ['groups' => $groups]);
    }

    public function datatable(Request $request)
    {
        return response($this->repository->datatable($request->all()));
    }

    public function delete(User $user_id)
    {
        $delete = $user_id->delete();
        if ($delete) {
            return response(['status' => true, 'message' => 'User deleted']);
        } else {
            return response(['message' => 'Failed to delete user'], Response::HTTP_UNPROCESSABLE_ENTITY);
        }
    }

    public function create(UserCreateRequest $request)
    {
        $request = $request->validated();

        $request['password'] = bcrypt($request['password']);

        $user = User::create($request);

        return response(['status' => true, 'data' => $user]);
    }

    public function get(User $user_id)
    {
        return response(['status' => true, 'data' => $user_id]);
    }

    public function getUserGroup(User $user_id)
    {
        $user = $user_id->append('group_ids');
        return response(['status' => true, 'data' => $user]);
    }

    public function updateUserGroup(User $user_id, UserUpdateGroupRequest $request)
    {
        $user = $user_id->groups()->sync($request->group_id);
        return response(['status' => true, 'data' => $user]);
    }

    public function update(User $user_id, UserUpdateRequest $request)
    {
        $request = $request->validated();

        if (isset($request['password'])) {
            $request['password'] = bcrypt($request['password']);
        }

        $user = $user_id->update($request);
        return response(['status' => true, 'data' => $user]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/dashboard/index.blade.php
@extends('layouts.master')
@section('page-title', 'Dashboard')
@section('page-header')
    <!--Page header-->
    <div class="page-header">
        <div class="page-leftheader">
            <h4 class="page-title mb-0">Dashboard</h4>
        </div>
    </div>
    <!--End Page header-->
@endsection
@section('content')

    </div>
    </div>
    <!-- End app-content-->
    </div>
@endsection
@section('js')

    <!--INTERNAL Peitychart js-->
    <script src="{{ URL::asset('assets/plugins/peitychart/jquery.peity.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/peitychart/peitychart.init.js') }}"></script>

    <!--INTERNAL Apexchart js-->
    <script src="{{ URL::asset('assets/js/apexcharts.js') }}"></script>

    <!--INTERNAL ECharts js-->
    <script src="{{ URL::asset('assets/plugins/echarts/echarts.js') }}"></script>

    <!--INTERNAL Chart js -->
    <script src="{{ URL::asset('assets/plugins/chart/chart.bundle.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/chart/utils.js') }}"></script>

    <!-- INTERNAL Select2 js -->
    <script src="{{ URL::asset('assets/plugins/select2/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('assets/js/select2.js') }}"></script>

    <!--INTERNAL Moment js-->
    <script src="{{ URL::asset('assets/plugins/moment/moment.js') }}"></script>

    <!--INTERNAL Index js-->
    <script src="{{ URL::asset('assets/js/index1.js') }}"></script>
@endsection

resources/views/admin/user/_add.blade.php
<div class="modal fade" id="modal-add" tabindex="-1" aria-labelledby="modal-add-title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-add-title">User Add</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form id="add-user-form" class="w-100">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="add-username" class="form-label">Username</label>
                                <input type="text" class="form-control" name="username" id="add-username"
                                    placeholder="Username">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="add-name" class="form-label">Name</label>
                                <input type="text" class="form-control" name="name" id="add-name"
                                    placeholder="Name">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="add-password" class="form-label">Password</label>
                                <input type="password" class="form-control" name="password" id="add-password"
                                    placeholder="Password">
                            </div>
                        </div>
                    </form>
                    <div class="col-12">
                        <div class="alert alert-danger show fade" id="add-alert-danger" role="alert"
                            style="display: none"><button type="button" class="close" aria-hidden="true"
                                id="add-alert-danger-close">×</button><span id="add-danger-message">-</span></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-info" id="btn-add-submit">Save</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/user/_edit.blade.php
<div class="modal fade" id="modal-edit" tabindex="-1" aria-labelledby="modal-edit-title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-edit-title">User Edit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form id="edit-user-form" class="w-100">
                        <input type="hidden" name="id" id="edit-id">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="edit-username" class="form-label">Username</label>
                                <input type="text" class="form-control" name="username" id="edit-username"
                                    placeholder="Username">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="edit-name" class="form-label">Name</label>
                                <input type="text" class="form-control" name="name" id="edit-name"
                                    placeholder="Name">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="edit-password" class="form-label">Password</label>
                                <input type="password" class="form-control" name="password" id="edit-password"
                                    placeholder="password">
                            </div>
                        </div>
                    </form>
                    <div class="col-12">
                        <div class="alert alert-danger show fade" id="edit-alert-danger" role="alert"
                            style="display: none"><button type="button" class="close" aria-hidden="true"
                                id="edit-alert-danger-close">×</button><span id="edit-danger-message">-</span></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-info" id="btn-edit-submit">Save</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/user/_group.blade.php
<div class="modal fade" id="modal-group" tabindex="-1" aria-labelledby="modal-group-title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-group-title">User Group</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form id="group-user-form" class="w-100">
                        <input type="hidden" name="id" id="group-id">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="group-group" class="form-label">Groups</label>
                                <select name="group_id[]" id="group-group" class="form-control select2"
                                    data-placeholder="Choose one/many" multiple>
                                    @foreach ($groups as $group)
                                        <option value="{{ $group->id }}">{{ ucwords($group->name) }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </form>
                    <div class="col-12">
                        <div class="alert alert-danger show fade" id="group-alert-danger" role="alert"
                            style="display: none"><button type="button" class="close" data-dismiss="alert"
                                aria-hidden="true" id="group-alert-danger-close">×</button><span
                                id="group-danger-message">-</span></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-info" id="btn-group-submit">Save</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/user/index.blade.php
@extends('layouts.master')
@section('page-title', 'User')
@section('css')
    <!-- Data table css -->
    <link href="{{ URL::asset('assets/plugins/datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="{{ URL::asset('assets/plugins/datatable/responsive.bootstrap4.min.css') }}" rel="stylesheet" />

    <!-- INTERNAL Select2 css -->
    <link href="{{ URL::asset('assets/plugins/select2/select2.min.css') }}" rel="stylesheet" />
    <style>
        .select2-search__field {
            width: 100% !important;
        }
    </style>
@endsection
@section('page-header')
    <!--Page header-->
    <div class="page-header">
        <div class="page-leftheader">
            <h4 class="page-title mb-0">User</h4>
        </div>
    </div>
    <!--End Page header-->
@endsection
@section('content')
    <!-- Row -->
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12">
            <!--table-->
            <div class="card">
                <div class="card-header">
                    <div class="card-title">User List</div>
                    <div class="card-options">
                        <div class="btn-group p-0">
                            <button class="btn btn-info" type="button" data-toggle="modal"
                                data-target="#modal-add">Add</button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="alert alert-success show fade" id="alert-success" role="alert" style="display: none">
                        <button type="button" class="close" aria-hidden="true" id="alert-success-close">×</button><span
                            id="success-message">-</span>
                    </div>
                    <div class="alert alert-danger show fade" id="alert-danger" role="alert" style="display: none"><button
                            type="button" class="close" aria-hidden="true" id="alert-danger-close">×</button><span
                            id="danger-message">-</span></div>
                    <div class="table-responsive">
                        <table class="table table-vcenter table-bordered text-nowrap w-100" id="datatable">
                        </table>
                    </div>
                </div>
            </div>
            <!--/table-->
        </div>
    </div>
    <!-- /Row -->
    </div>
    @include('admin.user._add')
    @include('admin.user._edit')
    @include('admin.user._group')
    </div><!-- end app-content-->
    </div>
@endsection
@section('js')
    @include('admin.user._script')
@endsection

resources/views/layouts/aside-menu.blade.php
    <aside class="app-sidebar">
        <div class="app-sidebar__logo">
            <a class="header-brand" href="{{ route('admin.dashboard') }}">
                <img src="" class="header-brand-img desktop-lgo" style="width: 50px; height: 50px;" alt="Logo">
                <img src="" class="header-brand-img dark-logo" style="width: 50px; height: 50px;" alt="Logo">
                <img src="" class="header-brand-img mobile-logo" alt="Logo">
                <img src="" class="header-brand-img darkmobile-logo" alt="Logo">
            </a>
        </div>
        <div class="app-sidebar__user">
            <div class="dropdown user-pro-body text-center">
                <div class="user-pic">
                    <img src="{{ URL::asset('assets/images/users/1.jpg') }}" alt="user-img"
                        class="avatar-xl rounded-circle mb-1">
                </div>
            </div>
        </div>
        <ul class="side-menu app-sidebar3">
            <li class="slide">
                <a class="side-menu__item" href="{{ route('admin.dashboard') }}">
                    <span class="side-menu__icon bg-white mx-auto d-flex align-items-center justify-content-center"><i
                            class="fa fa-dashboard" style="font-size: 1rem"></i></span>
                    <span class="side-menu__label ml-3">Dashboard</span>
                </a>
            </li>
            <li class="slide">
                <a class="side-menu__item" href="{{ route('admin.user.index') }}">
                    <span class="side-menu__icon bg-white mx-auto d-flex align-items-center justify-content-center"><i
                            class="fa fa-users" style="font-size: 1rem"></i></span>
                    <span class="side-menu__label ml-3">User</span>
                </a>
            </li>
        </ul>
    </aside>
    <!--aside closed-->

resources/views/layouts/custom-footer-scripts.blade.php
		<!-- Jquery js-->

        <!-- App js-->
        <script src="{{URL::asset('js/app.js')}}"></script>

		<!--Othercharts js-->
		<script src="{{URL::asset('assets/plugins/othercharts/jquery.sparkline.min.js')}}"></script>

		<!-- Circle-progress js-->
		<script src="{{URL::asset('assets/js/circle-progress.min.js')}}"></script>

		<!-- Jquery-rating js-->
		<script src="{{URL::asset('assets/plugins/rating/jquery.rating-stars.js')}}"></script>

		@yield('js')

        <!-- Custom js-->
        <script src="{{URL::asset('assets/js/custom.js')}}"></script>
        <script src="{{URL::asset('assets/js/custom-local.js')}}"></script>

resources/views/layouts/footer-scripts.blade.php
<!-- Back to top -->
<a href="#top" id="back-to-top"><i class="fe fe-chevrons-up"></i></a>

<!-- App js-->
<script src="{{ URL::asset('js/app.js') }}"></script>

<!--Othercharts js-->
<script src="{{ URL::asset('assets/plugins/othercharts/jquery.sparkline.min.js') }}"></script>

<!-- Circle-progress js-->
<script src="{{ URL::asset('assets/js/circle-progress.min.js') }}"></script>

<!-- Jquery-rating js-->
<script src="{{ URL::asset('assets/plugins/rating/jquery.rating-stars.js') }}"></script>

<script src="{{ URL::asset('assets/plugins/sidemenu/sidemenu.js') }}"></script>

<!-- P-scroll js-->
<script src="{{ URL::asset('assets/plugins/p-scrollbar/p-scrollbar.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/p-scrollbar/p-scroll1.js') }}"></script>

<!-- Simplebar JS -->
<script src="{{ URL::asset('assets/plugins/simplebar/js/simplebar.min.js') }}"></script>

@yield('js')

<!-- Custom js-->
<script src="{{ URL::asset('assets/js/custom.js') }}"></script>
<script src="{{ URL::asset('assets/js/custom-local.js') }}"></script>

<script>
    $('#btn-logout').click(function() {
        loadingUtils.btnBlock(this);
        $.ajax({
            type: 'POST',
            url: '{{ route('auth.logout') }}',
            dataType: 'json'
        }).done(function(response) {
            if (response.status) {
                window.location.href = response.redirect
            }
        }).fail(function(err) {
            jsonErr = err.responseJSON;

            if ('errors' in jsonErr) {
                message = [];
                Object.entries(jsonErr.errors).forEach(([key, val]) => {
                    message.push(val.join('<br>'))
                });

                alertUtils.showFailed(message.join('<br>'))
            } else if ('message' in jsonErr) {
                alertUtils.showFailed(jsonErr.message)
            } else {
                alertUtils.showFailed('Failed connecting to serve, please try again')
            }
        }).always(function() {
            loadingUtils.btnUnblock('#btn-logout')
        })

    });
</script>

resources/views/login.blade.php
@extends('layouts.master2')
@section('css')
@endsection
@section('content')
    <div class="page">
        <div class="page-content">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="">
                            <div class="text-white">
                                <div class="card-body">
                                    <h2 class="display-4 mb-2 font-weight-bold text-center"><strong>Login</strong></h2>
                                    <h4 class="text-white-80 mb-7 text-center">Sign In to your account</h4>
                                    <div class="row">
                                        <div class="col-9 d-block mx-auto">
                                            <div class="alert alert-danger show fade" id="alert-danger" role="alert"
                                                style="display: none"><button type="button" class="close"
                                                    aria-hidden="true" id="alert-danger-close">×</button><span
                                                    id="danger-message">-</span></div>
                                            <form id="login-form">
                                                @csrf
                                                <div class="input-group mb-4">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">
                                                            <i class="fe fe-user"></i>
                                                        </div>
                                                    </div>
                                                    <input type="text" class="form-control" placeholder="Username"
                                                        name="username">
                                                </div>
                                                <div class="input-group mb-4">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">
                                                            <i class="fe fe-lock"></i>
                                                        </div>
                                                    </div>
                                                    <input type="password" class="form-control" placeholder="Password"
                                                        name="password">
                                                </div>
                                            </form>
                                            <div class="row">
                                                <div class="col-12">
                                                    <button type="button" class="btn btn-danger btn-block px-4"
                                                        id="login-button">Login</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 d-none d-md-flex align-items-center">
                        <img src="{{ URL::asset('assets/images/photos/1.jpg') }}" alt="img">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script>
        function initCreateForm() {
            var form = $('#login-form');

            var validator = form.validate({
                errorClass: 'invalid-feedback text-white',
                errorElement: 'div',
                errorPlacement: (error, element) => {
                    error.insertAfter(element)
                },
                highlight: element => {
                    $(element).addClass(['is-invalid', 'state-invalid', 'border-danger'])
                },
                unhighlight: element => {
                    $(element).removeClass(['is-invalid', 'state-invalid', 'border-danger'])
                },
                rules: {
                    username: {
                        required: true
                    },
                    password: {
                        required: true
                    }
                }
            })

            $('#login-button').click(function() {
                var isValid = form.valid();
                if (isValid) {
                    loadingUtils.btnBlock('#login-button');
                    $.ajax({
                        type: 'POST',
                        url: '{{ route('auth.login') }}',
                        data: $('#login-form').serialize(),
                        dataType: 'json'
                    }).done(function(response) {
                        if (response.status) {
                            window.location.href = response.redirect
                        }
                    }).fail(function(err) {
                        jsonErr = err.responseJSON;

                        if ('errors' in jsonErr) {
                            message = [];
                            Object.entries(jsonErr.errors).forEach(([key, val]) => {
                                message.push(val.join('<br>'))
                            });

                            alertUtils.showFailed(message.join('<br>'))
                        } else if ('message' in jsonErr) {
                            alertUtils.showFailed(jsonErr.message)
                        } else {
                            alertUtils.showFailed('Failed connecting to serve, please try again')
                        }
                    }).always(function() {
                        loadingUtils.btnUnblock('#login-button');
                    })
                }
            })
        }

        $(document).ready(function() {
            initCreateForm()
        });
    </script>
@endsection